### ISSUE TITLE
Update time in list view

### ISSUE THREAD

**Issue by sindrefs** [dagstuan/skredvarselGarmin#7]
Can the user trust that the forecast in the list view is up-to-date? Is there som timeout or fall-back screen? If not, it would've be great to have the time of last update also in the list view. 

I also want to add that the widget is very promising, and I look forward to use it for easter when I'm in the mountains. Impressive work! 👏💯

**Comment by dagstuan** [comment]
There is a fallback. Stale data is displayed for a maximum of 24 hours. But adding a "last fetched" to the footer of the timeline-view should be possible yes 👍

**Comment by dagstuan** [comment]
This is fixed in #8 and released as v1.5.0 in the Garmin Store.

The timelines are fetched independently, so the fetched time shown is the oldest region.
